# Generated by Django 5.0.4 on 2024-04-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('places', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=5)),
            ],
        ),
    ]
